Ik contact us
Gleb-Yas/brainstorm-battalion-team-project pull request #13
Opened 2024-06-05 13:29 UTC by ihorkharatin

Updated mobile 

updated input form required.

2024-06-05 17:54 UTC, Gleb-Yas requested changes
ок, давай пофіксимо це і можна буде робити адаптив

2024-06-05 17:54 UTC, Gleb-Yas commented on src/partials/contact.html
> +      <h3 class="contact-us-heading">Contact Us</h3>
це має бути заголовок H2

2024-06-05 17:54 UTC, Gleb-Yas commented on src/partials/contact.html
> +              name="coment-user"
name="comment-user" має бути з 2ма "m"

2024-06-05 17:54 UTC, Gleb-Yas commented on src/partials/contact.html
> +            <button class="btn-send" type="submit">
варто додати "aria-label" (опис що ця кнопка робить)

2024-06-05 17:54 UTC, Gleb-Yas commented on src/partials/contact.html
> +        <label class="contact-us-label-text">
у лейбла має бути атрибут for="", таке саме як id інпута

2024-06-05 17:54 UTC, Gleb-Yas commented on src/partials/contact.html
> +        <input
label має бути в кожного інпута, навіть якщо порожній

2024-06-05 17:54 UTC, Gleb-Yas commented on src/css/contact.css
> +  margin: 0 auto;
тут марджин не потрібен, він уже є в body

2024-06-05 17:54 UTC, Gleb-Yas commented on src/css/contact.css
> +  text-align: left;
text-align може не спрацювати якщо ти задаш якісь параметри флексу, краще задати align-self

2024-06-06 13:54 UTC, ihorkharatin commented on src/partials/contact.html
> +      <h3 class="contact-us-heading">Contact Us</h3>
Виправив

2024-06-06 13:54 UTC, ihorkharatin commented on src/partials/contact.html
> +              name="coment-user"
Виправив

2024-06-06 13:57 UTC, ihorkharatin commented on src/partials/contact.html
> +            <button class="btn-send" type="submit">
Виправив

2024-06-06 13:58 UTC, ihorkharatin commented on src/partials/contact.html
> +        <label class="contact-us-label-text">
Виправив

2024-06-06 13:58 UTC, ihorkharatin commented on src/partials/contact.html
> +        <input
Виправив

2024-06-06 13:58 UTC, ihorkharatin commented on src/css/contact.css
> +  margin: 0 auto;
Виправив

2024-06-06 14:07 UTC, ihorkharatin commented on src/css/contact.css
> +  text-align: left;
Виправив

2024-06-06 14:43 UTC, closed without merging