Ik contact us
Gleb-Yas/brainstorm-battalion-team-project pull request #18
Opened 2024-06-06 14:46 UTC by ihorkharatin

Оновлена версія для мобілки та планшета

2024-06-06 15:13 UTC, ihorkharatin commented
Добавив коменти і зробив Push origin знову.

2024-06-06 15:16 UTC, ihorkharatin commented
Тестую як воно працює

2024-06-06 19:34 UTC, Gleb-Yas requested changes

2024-06-06 19:34 UTC, GYaskey commented on src/partials/contact.html
> +             width=""
треба додати базовву ширину і висоту

2024-06-06 19:34 UTC, GYaskey commented on src/css/contact.css
> +  padding-bottom: 30px;
паддінги змінюються на планшеті і десктопі

2024-06-06 19:34 UTC, GYaskey commented on src/css/contact.css
> +.contact-us-container-form {
цей окремий контейнер в цілому нічого не задає
всі властивості ідуть від форми
якщо хочеш - можна прибрати

2024-06-06 19:34 UTC, GYaskey commented on src/css/contact.css
> +    border-radius: 50px;
цей радіус перенесеться з планшета, можна прибрати

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +    height: 556px;
тут висота не має бути визначена
вона має утворюватись від внутрішнього контента
поміряй кожен елемент і задай потрібний розмір там

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +  align-self: flex-start;
це не флекс - бокс, на нього не подіє цей параметр

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +    align-self: center;
цей теж не подіє
це флексова команда

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +  padding: 12px 136px 12px 14px;
тут падінг має бути рівномірний з кожної сторони
12px 14px

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +  margin-bottom: 18px;
в тебе бекграунд білий
по макету має бути прозорий

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +  outline: transparent;
не заданий стиль тексту
в тебе він сірий, має бути чорний і тд

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +    align-self: center;
теж не спрацює

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +  padding-left: 14px;
падінги мають бути по всім сторонам

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +  height: 100%;
висота textarea відрізняється
це впливає на загальний розмір  контейнера
якщо пофіксити ці та інші розбіжності - не треба буде задавати загальну висоту

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +  border: 1px solid #3350e9;
ми в діскорді домовились додати анімацію
подивись в каналі notes-and-resourses

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +  border-radius: 12px;
textarea треба зафіксувати, зараз є можливість його розтягувати
![Screenshot 2024-06-06 at 22 29 50](https://github.com/Gleb-Yas/brainstorm-battalion-team-project/assets/91141358/cf4bd14f-69f9-416b-9376-5e3e7b43faf5)

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +  margin-top: 28px;
краще прибрати верхній маржин тут і додати нижній маржин на останній лейбл (в якому textarea)

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +.contact-us-image {
це все уже задано на загальний тег img
можна прибрати

2024-06-06 19:34 UTC, Gleb-Yas commented on src/css/contact.css
> +.btn-send {
кнопці треба додати ховер і фокус як на макеті з анімацією

2024-06-06 22:09 UTC, ihorkharatin commented on src/css/contact.css
> +    border-radius: 50px;
Я перевіряв на мобілкі 30 радіус на планшеті та компі 50 подивись

2024-06-06 22:10 UTC, ihorkharatin commented on src/css/contact.css
> +.contact-us-container-form {
Цей контейнер в мене вирівнює колонки і стовпчик. Андрій сьогодні порадив його створити обгорнути форму.

2024-06-06 22:13 UTC, ihorkharatin commented on src/css/contact.css
> +    height: 556px;
я пробував порізному контейнер получається меньше по висоті за фото. Тому зафіксував. Я все перепробував не знаю де знайти. Якщо я приберу то контейнер уменьшиться. Тут я не знаю де

2024-06-06 22:15 UTC, ihorkharatin commented on src/css/contact.css
> +  border: 1px solid #3350e9;
добавив

2024-06-06 22:16 UTC, ihorkharatin commented on src/css/contact.css
> +  border-radius: 12px;
зафіксував

2024-06-06 22:48 UTC, ihorkharatin commented on src/partials/contact.html
> +             width=""
Пробував. Тоді тянеться ця ширина на планшет і десктоп. Я прибрав її.

2024-06-06 22:53 UTC, ihorkharatin commented on src/css/contact.css
> +  padding-bottom: 30px;
Ви правив добавив

2024-06-06 22:58 UTC, ihorkharatin commented on src/css/contact.css
> +  margin-top: 28px;
Я зробив так тому що на деск топі не діяв падінг від textarea

2024-06-06 22:59 UTC, ihorkharatin commented on src/css/contact.css
> +.contact-us-image {
Прибрав

2024-06-06 23:10 UTC, ihorkharatin commented on src/css/contact.css
> +.btn-send {
Добавив

2024-06-06 23:13 UTC, ihorkharatin commented
Все виправив лише

1 Якщо фото задати фіксовану ширину вона тянеться на десктоп і планшет
2 Форму поки фіксую якщо прибрати то вона меньша за фото. Поки не знаю попробую ще

2024-06-07 10:45 UTC, Gleb-Yas commented on src/partials/contact.html
> +             width=""
ти можеш ці розміри задати через стилі в медіа запитах або в кожному source
подивись як це зроблено в hero

2024-06-07 17:46 UTC, ihorkharatin commented on src/partials/contact.html
> +             width=""
Добавив

2024-06-07 17:46 UTC, ihorkharatin commented on src/css/contact.css
> +    height: 556px;
Виправив

2024-06-07 17:48 UTC, ihorkharatin commented on src/css/contact.css
> +  align-self: flex-start;
Виправив на  text-align: start;

2024-06-07 17:49 UTC, ihorkharatin commented on src/css/contact.css
> +    align-self: center;
Виправив

2024-06-07 17:52 UTC, ihorkharatin commented on src/css/contact.css
> +  padding: 12px 136px 12px 14px;
Скопіював що було на макеті. Виправив

2024-06-07 17:55 UTC, ihorkharatin commented on src/css/contact.css
> +  margin-bottom: 18px;
Виправив. Не додивився

2024-06-07 18:01 UTC, ihorkharatin commented on src/css/contact.css
> +  outline: transparent;
Добавив плейхолдеру колір чорний

2024-06-07 18:03 UTC, ihorkharatin commented on src/css/contact.css
> +    align-self: center;
виправив

2024-06-07 18:04 UTC, ihorkharatin commented on src/css/contact.css
> +  padding-left: 14px;
Виправив

2024-06-07 18:05 UTC, ihorkharatin commented on src/css/contact.css
> +  height: 100%;
Виправив на мобілкі 84 а десктопі 90

2024-06-08 10:24 UTC, Gleb-Yas approved these changes

2024-06-08 10:24 UTC, GYaskey commented on src/css/contact.css
> +    border-radius: 50px;
все вірно
але ти дублюєш однакове значення на планшеті і десктопі
строка 64 і 69 однакові
69 не потрібна бо радіус 50 перенесеться з планшета

2024-06-08 10:24 UTC, GYaskey commented on src/css/contact.css
> +  align-self: flex-start;
оце не прибрано

2024-06-08 10:24 UTC, GYaskey commented on src/css/contact.css
> +    align-self: center;
це теж

2024-06-08 10:24 UTC, Gleb-Yas commented on src/css/contact.css
> +.btn-send {
у кнопки теж має бути анімація

2024-06-08 10:24 UTC, merged