edited backgroung color-header
Gleb-Yas/brainstorm-battalion-team-project pull request #22
Opened 2024-06-07 13:00 UTC by OlhaMy

2024-06-07 15:12 UTC, Gleb-Yas requested changes

2024-06-07 15:12 UTC, Gleb-Yas commented on src/css/header.css
> +    transform: translateX(0);
анімація не відпрацьовує бо їй нема чого анімувати
має бути   transform: translateX(100%);

2024-06-07 15:12 UTC, Gleb-Yas commented on src/css/header.css
> +    transition: transform 250ms cubic-bezier(.4,0,.2,1);
тут уже не потрібен транзішн

2024-06-07 20:01 UTC, OlhaMy commented on src/css/header.css
> +    transition: transform 250ms cubic-bezier(.4,0,.2,1);
якщо так прописати, то взагалі вікно не відпрацьовує....я тестила в css багато опцій. Зроби Merging, щоб вирівнявся container i background, а це запитаємо Андрія в неділю.

2024-06-07 20:39 UTC, OlhaMy reviewed
added hover/focus

2024-06-08 10:46 UTC, Gleb-Yas approved these changes

2024-06-08 10:46 UTC, merged