update
Gleb-Yas/brainstorm-battalion-team-project pull request #29
Opened 2024-06-08 14:34 UTC by ihorkharatin

поправки
У кнопки нема анімації на ховер і фокус  (Добавив)
У заголовка, текста над формою і плейсхолдерів змінюються шрифти на різних екранах (Виправив)
Відстань між полем для коментарів і кнопкою відрізняється від макета, подивись чому це може бути (28 , 32 32 там так і було

2024-06-08 18:03 UTC, Gleb-Yas requested changes

2024-06-08 18:03 UTC, GYaskey commented on src/css/contact.css
> +    font-size: 16px;
разом з розміром шрифта змінюється і line-height

2024-06-08 18:03 UTC, GYaskey commented on src/css/contact.css
>  .contact-us-input {
в тебе чомусь зникла анімація з input і textarea

2024-06-08 18:03 UTC, Gleb-Yas commented on src/partials/contact.html
>                maxlength="40"
в інпуті user-name в тебе id не співпадає з лейблом
<img width="772" alt="Screenshot 2024-06-08 at 20 58 20" src="https://github.com/Gleb-Yas/brainstorm-battalion-team-project/assets/91141358/5d6e36e1-ca24-4e93-98e2-39f6c97c252e">

2024-06-08 18:03 UTC, Gleb-Yas commented on src/partials/contact.html
>                required
у textarea відсутній "id"

2024-06-08 18:18 UTC, ihorkharatin commented on src/css/contact.css
> +    font-size: 16px;
Добавив

2024-06-08 18:21 UTC, ihorkharatin commented on src/css/contact.css
>  .contact-us-input {
добавив

2024-06-08 18:22 UTC, ihorkharatin commented on src/partials/contact.html
>                maxlength="40"
виправив

2024-06-08 18:24 UTC, ihorkharatin commented on src/partials/contact.html
>                required
добавив

2024-06-09 06:16 UTC, Gleb-Yas approved these changes

2024-06-09 06:16 UTC, merged