Lantukh hero
Gleb-Yas/brainstorm-battalion-team-project pull request #7
Opened 2024-06-04 20:40 UTC by VadymLantukh

2024-06-04 20:50 UTC, Gleb-Yas requested changes
edit container size

2024-06-05 08:56 UTC, Gleb-Yas requested changes

2024-06-05 08:56 UTC, Gleb-Yas commented on src/css/hero.css
> +  width: 375px;
мобільний контейнер - 355px.
ми ж говорили що ми орієнтуємо контейнер по сірим контентним лініям (layout)
сам контент - 335px в ширину

але на саму секцію взагалі не потрібна ширина

2024-06-05 08:56 UTC, Gleb-Yas commented on src/css/hero.css
> +  height: 732px;
як і висота - вона сама себе має визначити за рахунок контента

2024-06-05 08:56 UTC, Gleb-Yas commented on src/css/hero.css
> +    height: 900px;
те саме - висота і ширина не потрібна - вона визначиться контейнером, який ти відсуваєш паддінгами

2024-06-05 08:56 UTC, Gleb-Yas commented on src/partials/hero.html
> +    <div class="hero-container">
тут не треба створювати ще один додатковий div - можна задати hero-container як додатковий клас поруч з container (на випадок якщо треба перевизначити щось в цьому конкретному контейнері)
hero-container стоїть нижче в коді і перевизначить якісь параметри якщо вони вже були задані в .container

2024-06-05 08:56 UTC, Gleb-Yas commented on src/css/hero.css
> +    width: 1150px;
те саме - секція не міняє розмір, вона міняється разом з екраном
тут потрібні розміри тільки якщо в тебе є background image

2024-06-05 08:56 UTC, Gleb-Yas commented on src/partials/hero.html
> +        <a class="hero-link-down" href="">Scroll down</a>
є сенс обʼєднати кнопку і 3 портрети в один дів і зробити їх флексом
зможеш нормально позиціонувати їх відносно текста на всіх екранах

2024-06-05 08:56 UTC, Gleb-Yas commented on src/partials/hero.html
> +      <img
а мейн фото як раз варто виділити окремо, бо воно не звʼязано з портретами і кнопкою

2024-06-05 08:56 UTC, Gleb-Yas commented on src/css/hero.css
> +.hero-image-box {
в цей флекс в тебе входить 3 елементи - портрети, кнопка і велика картинка
вона не поміститься коли ти зміниш розміри для планшета і десктопа

сюди ж по розмітці попадає і кнопка

2024-06-05 11:43 UTC, VadymLantukh commented on src/partials/hero.html
> +    <div class="hero-container">
Я його переіменував той div, що не плутатись, але він мені потрібен для позиціювання, бо по ньому я робив все інше позиціювання і той div не огортає все, як container

2024-06-05 11:46 UTC, VadymLantukh commented on src/partials/hero.html
> +        <a class="hero-link-down" href="">Scroll down</a>
Ну я його зробив, бо там розміри інші на макетах і робив позиціювання

2024-06-05 11:46 UTC, VadymLantukh commented on src/partials/hero.html
> +      <img
Так це зробив це в точку

2024-06-05 22:07 UTC, Gleb-Yas requested changes

2024-06-05 22:07 UTC, GYaskey commented on src/partials/hero.html
> +<section class="hero-section">
додати id на секцію - таку саму як назва html-файла

2024-06-05 22:07 UTC, Gleb-Yas commented on src/css/hero.css
> +}
нема стилів для головного зображення (border-radius і background: linear-gradient)

2024-06-05 22:07 UTC, Gleb-Yas commented on src/partials/hero.html
> +    <picture>
ти прибрав головну картинку за div, а у картинки нема класу => ти не можеш її стилізувати

бачу є класс на самому img, але можливо (не впевнений) стилізація може не спрацювати на соурси
можемо це уточнити у Андрія

2024-06-06 05:02 UTC, VadymLantukh commented on src/css/hero.css
> +}
Я це додав, але змін не бачу, треба за це у Андрія питати

2024-06-06 05:03 UTC, VadymLantukh commented on src/partials/hero.html
> +    <picture>
Працює)

2024-06-06 05:03 UTC, VadymLantukh commented on src/css/hero.css
> +}
Хоча, якщо дати 100px border radius то працює

2024-06-06 05:07 UTC, VadymLantukh commented on src/partials/hero.html
> +<section class="hero-section">
id="hero" таке поставив

2024-06-06 05:08 UTC, VadymLantukh commented on src/css/hero.css
> +}
background не працює

2024-06-06 15:07 UTC, Gleb-Yas approved these changes

2024-06-06 15:07 UTC, merged