created footer
Gleb-Yas/brainstorm-battalion-team-project pull request #8
Opened 2024-06-04 23:51 UTC by anastasia-boichenko

2024-06-05 10:48 UTC, Gleb-Yas requested changes

2024-06-05 10:48 UTC, Gleb-Yas commented on src/css/footer.css
> +  background-color: #0c0c0c;
все вірно, але в наступних апдейтах можеш це прибрати - додав color і background-color до "body"

2024-06-05 10:48 UTC, Gleb-Yas commented on src/partials/footer.html
> +  <div class="footer-container">
додай будь-ласка додатковий класс container, щоб на нього відпрацьовували загальні стилі

2024-06-05 10:48 UTC, Gleb-Yas commented on src/partials/footer.html
> +              <use href="../img/icons.svg#icon-facebook" />
треба прибрати з кожного href одну крапку на початку. браузер бере за вихідну точку index.html і для нього папка img лежить на одному рівні
те саме для кожного підключеного зображення

2024-06-05 10:48 UTC, Gleb-Yas commented on src/partials/footer.html
> +    <a class="footer-phone-number">+380 (68) 443-94-26</a>
посиланню треба задати href="tel:+380684439426"

2024-06-05 10:48 UTC, Gleb-Yas commented on src/partials/footer.html
> +          <a href="" class="footer-nav-link">Home</a>
посилання можна зробити через якоря на #hero, #about і тд
я попросив усіх задати id своїм секціям такі самі як і назви файлів .html

2024-06-05 10:48 UTC, Gleb-Yas commented on src/partials/footer.html
> +        1678 S. Pionee <br />
краще зробити footer-adress флексом, задати йому обмежену ширину і прибрати <br>
в такому варіанті як зараз ти не зможеш міняти переноси текста на планшеті і десктопі

2024-06-05 10:48 UTC, Gleb-Yas commented on src/partials/footer.html
> +      <p>©2023 The Watch Spot. All rights reserved.</p>
в такому варіанті може не зчитати символ копірайту
варто задати його кодом
можна взяти звідси https://www.toptal.com/designers/htmlarrows/symbols/

2024-06-05 10:48 UTC, Gleb-Yas commented on src/partials/footer.html
> +      <a>Terms of Service</a>
гуд, але додай ще href пліз

2024-06-05 10:48 UTC, Gleb-Yas commented on src/css/footer.css
> +  padding: 14px;
паддінг не спрацює бо в тебе вже є  text-align: center і  justify-content: center;
і там різні паддінги по вертикалі і горизонталі

можна просто видалити

2024-06-05 10:48 UTC, Gleb-Yas commented on src/css/footer.css
> +  gap: 8px 16px;
в цілому гуд
але може зручніше буде прописати окремо через row-gap і column-gap ?

2024-06-05 10:48 UTC, Gleb-Yas commented on src/css/footer.css
> +  position: relative;
а нащо йому position: relative якщо ми його позиціонуємо маржином, а те що в середині - через флекс?

2024-06-05 22:08 UTC, anastasia-boichenko commented on src/css/footer.css
> +  gap: 8px 16px;
Але дивись (не знаю чи зображення прикріпить сюди), коли я забираю цей падінг, номер зістрибує із середини. Я теж спочатку не думала його прописувати, проте з ним номер стоїть всередині як треба.

2024-06-06 16:34 UTC, Gleb-Yas requested changes
правки прийняв, але треба пофіксити розмір контейнера
він переписує базовий розмір контейнера

2024-06-06 16:34 UTC, GYaskey commented on src/partials/footer.html
> +          <a href="" class="footer-nav-link" href="../index.html">Home</a>
в тебе тут двічі href доданий
видали порожній пліз

2024-06-06 16:34 UTC, Gleb-Yas commented on src/partials/footer.html
>        <p class="footer-adress">
отут так і не прибарні  "br /"

2024-06-06 16:34 UTC, Gleb-Yas commented on src/css/footer.css
> +  width: 355px;
color, background color, width можна прибрати

2024-06-06 16:34 UTC, Gleb-Yas commented on src/css/footer.css
>    padding: 40px 28px 28px 28px;
ці паддінги перебивають падінги задані в reset.css
по ітогу в тебе контент виходить 355 px, а має бути 335px (іще 20px мають займати падінги)
виділи в середині .container інший div і спробуй розмістити контент в ньому

2024-06-07 10:15 UTC, Gleb-Yas requested changes

2024-06-07 10:15 UTC, GYaskey commented on src/css/footer.css
> +  margin-bottom: 20px;
оцей марджин заданий на іконку і розтягує її
перенеси цей марджин на загальний список footer-socials-list

![Screenshot 2024-06-07 at 13 17 09](https://github.com/Gleb-Yas/brainstorm-battalion-team-project/assets/91141358/635ec05a-207e-48d9-a70f-cf4f71366bb5)

2024-06-07 11:54 UTC, Gleb-Yas approved these changes

2024-06-07 11:54 UTC, merged